image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - command: python3 welcome.py
    - init: pipenv install
      command: >
        pipenv run migrate;
        pipenv run start;