image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: pipenv install
      command: >
        pipenv run migrate;
        pipenv run start;
        python3 welcome.py;
